version: "3"
services:
  app:
    build: ./src/Authentication
    depends_on: :
      - "db"
    ports:
      - "5052:5000"

  db:
    image: mysql:5.7
    ports:
      - "32010:3310"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/db:/docker-entrypoint-initdb.d/:ro